config/routes.rb
Rails.application.routes.draw do
  resources :baseballs
  resources :players
  get :team, to: 'baseballs#team'
  root 'baseballs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/baseballs_controller.rb
class BaseballsController < ApplicationController
  def index
  end

  def team
    output = Player.all.to_json
    render json: output 
  end

  def new
    @player = Player.new
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to players_path
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to players_path
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      redirect_to players_path
    end
  end

  private
  def player_params
    params.require(:player).permit(:name, :age, :height, :weight, :hometown, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baseballs_helper.rb
module BaseballsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseball</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/navbar' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with model: player do |f| %>
  <div class="bg-white shadow rounded-lg p-6">
    <div class="grid lg:grid-cols-2 gap-6">
      <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
        <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
          <p>
            <label for="name" class="bg-white text-gray-600 px-1"><%= f.label t(:name) %></label>
          </p>
        </div>
        <p>
          <%= f.text_field :name, autocomplete:"false", tabindex:"0", type:"text", class:"py-1 px-1 text-gray-900 outline-none block h-full w-full" %>
        </p>
      </div>
      <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
        <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
          <p>
            <label for="name" class="bg-white text-gray-600 px-1"><%= f.label t(:photo) %></label>
          </p>
        </div>
        <p>
          <%= f.file_field :photo, autocomplete:"false", tabindex:"0", class:"py-1 px-1 text-gray-900 outline-none block h-full w-full" %>
        </p>
      </div>
      <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
        <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
          <p>
            <label for="lastname" class="bg-white text-gray-600 px-1"><%= f.label t(:age) %></label>
          </p>
        </div>
        <p>
          <%= f.text_field :age, autocomplete:"false", tabindex:"0", type:"text", class:"py-1 px-1 text-gray-900 outline-none block h-full w-full" %>
        </p>
      </div>
      <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
        <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
          <p>
            <label for="username" class="bg-white text-gray-600 px-1"><%= f.label t(:height) %></label>
          </p>
        </div>
        <p>
          <%= f.text_field :height, autocomplete:"false", tabindex:"0", type:"text", class:"py-1 px-1 text-gray-900 outline-none block h-full w-full" %>
        </p>
      </div>
      <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
        <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
          <p>
            <label for="password" class="bg-white text-gray-600 px-1"><%= f.label t(:weight) %></label>
          </p>
        </div>
        <p>
          <%= f.text_field :weight, autocomplete:"false", tabindex:"0", type:"text", class:"py-1 px-1 text-gray-900 outline-none block h-full w-full" %>
        </p>
      </div>
      <div class="border focus-within:border-blue-500 focus-within:text-blue-500 transition-all duration-500 relative rounded p-1">
        <div class="-mt-4 absolute tracking-wider px-1 uppercase text-xs">
          <p>
            <label for="password" class="bg-white text-gray-600 px-1"><%= f.label t(:hometown) %></label>
          </p>
        </div>
        <p>
          <%= f.text_field :hometown, autocomplete:"false", tabindex:"0", type:"text", class:"py-1 px-1 text-gray-900 outline-none block h-full w-full" %>
        </p>
      </div>
    </div>
    <div class="border-t mt-6 pt-3">
      <button >
        <%= f.submit t(:new_player), class:"rounded text-gray-100 px-3 py-1 bg-blue-500 hover:shadow-inner hover:bg-blue-700 transition-all duration-300" %>
      </button>
    </div>
  </div>
<% end %>

app/views/players/edit.html.erb
<%= render 'form', player: @player %>

app/views/players/index.html.erb
<div class="container mx-auto">
  <%= link_to '新增球員', new_player_path, class:'bg-blue-500 hover:bg-blue-700 text-white font-bold p-4 rounded-full' %>
<div class="w-full p-4 flex">
  <% @players.each do |p| %>
    <div class="m-4 max-w-sm rounded overflow-hidden shadow-lg d-flex">
      <%= image_tag p.photo.variant(resize_to_limit: [200, 200]) if p.photo.present? %>
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2"><%= p.name %></div>
        <p class="text-gray-700 text-base">
          年齡<%= p.age %>
        </p>
      </div>
      <div class="px-6 py-4">
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2"><%= link_to '編輯', edit_player_path(p) %></span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2"><%= link_to '刪除', player_path(p), method: 'delete' %></span>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/players/new.html.erb
<%= render 'form', player: @player %>

app/views/shared/_navbar.html.erb
<!-- component -->
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
  <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
    <div class="flex flex-row items-center justify-between">
      <a href="<%= root_path %>" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline"><img src="https://scontent.ftpe3-2.fna.fbcdn.net/v/t1.0-9/376377_364232133650580_1926257042_n.jpg?_nc_cat=101&_nc_sid=85a577&_nc_ohc=wr7uiuRwOv4AX--m1QF&_nc_ht=scontent.ftpe3-2.fna&oh=1d46cb4dfa9f765c12a5656f94de8e56&oe=5F5EAA87" alt="kupao" style="width: 100px;"></a>
      <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
    <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
      <a class="px-4 py-2 mt-2 text-sm font-semibold text-gray-900 bg-gray-200 rounded-lg dark-mode:bg-gray-700 dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="<%= team_path %>"><%= t(:team) %></a>
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="<%= players_path %>"><%= t(:all_player) %></a>
      <div @click.away="open = false" class="relative" x-data="{ open: false }">
        <button @click="open = !open" class="flex flex-row items-center w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:focus:bg-gray-600 dark-mode:hover:bg-gray-600 md:w-auto md:inline md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
          <span>選項</span>
          <svg fill="currentColor" viewBox="0 0 20 20" :class="{'rotate-180': open, 'rotate-0': !open}" class="inline w-4 h-4 mt-1 ml-1 transition-transform duration-200 transform md:-mt-1"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
          <div class="px-2 py-2 bg-white rounded-md shadow dark-mode:bg-gray-800">
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Link #1</a>
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Link #2</a>
            <a class="block px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="#">Link #3</a>
          </div>
        </div>
      </div>    
    </nav>
  </div>
</div>